#@follow_tag(registry-proxy.engineering.redhat.com/rh-osbs/ubi8:latest)d
FROM registry-proxy.engineering.redhat.com/rh-osbs/ubi8:8.7-849 AS builder

ENV BUILD_VERSION=v0.23-rh
ENV SOURCE_GIT_COMMIT=${CI_VECTOR_UPSTREAM_COMMIT}
ENV SOURCE_GIT_URL=${CI_VECTOR_UPSTREAM_URL}

ENV REMOTE_SOURCE=${REMOTE_SOURCE:-.}

## EXCLUDE BEGIN ##
ENV REMOTE_SOURCE=${REMOTE_SOURCE}/app
## EXCLUDE END ##

RUN ls -al /etc/yum.repos.d/
RUN rm /etc/yum.repos.d/ubi.repo
ADD 8.7-compose.repo /etc/yum.repos.d


RUN INSTALL_PKGS=" \
      rust-toolset \
      gcc-c++ \
      cmake \
      make \
      git \
      openssl-devel \
      llvm-toolset \
      cyrus-sasl \
      python36 \
      llvm \
      cyrus-sasl-devel \
      libtool \
      " && \
    yum install -y $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all

RUN mkdir -p /src

WORKDIR /src
COPY ${REMOTE_SOURCE} /src

RUN PROTOC=/src/thirdparty/protoc/protoc-linux-$(arch) make build

# Copying to /usr/bin because copying from /src/target/release/vector to next stage doesnt seem to work in OSBS with imagebuilder
RUN cp /src/target/release/vector /usr/bin

#@follow_tag(registry-proxy.engineering.redhat.com/rh-osbs/ubi8:latest)
FROM registry-proxy.engineering.redhat.com/rh-osbs/ubi8:8.7-849

COPY --from=builder /usr/bin/vector /usr/bin/

WORKDIR /usr/bin
CMD ["/usr/bin/vector"]

LABEL \
        License="Apache-2.0" \
        io.k8s.description="Vector container for collection of container logs" \
        io.k8s.display-name="Vector" \
        io.openshift.tags="logging,vector" \
        vendor="Red Hat" \
        name="openshift-logging/vector-rhel8" \
        com.redhat.component="logging-vector-container" \
        io.openshift.maintainer.product="OpenShift Container Platform" \
        io.openshift.build.commit.id=${CI_VECTOR_UPSTREAM_COMMIT} \
        io.openshift.build.source-location=${CI_VECTOR_UPSTREAM_URL} \
        io.openshift.build.commit.url=${CI_VECTOR_UPSTREAM_URL}/commit/${CI_VECTOR_UPSTREAM_COMMIT} \
        version=v0.23
